name: Build LaTeX document
on:
  push:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: src/main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: src/main.aux
          compiler: bibtex
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: src/main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: src/main.pdf
