name: Build LaTeX document
on:
  push:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          working-directory: src
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: biber main
        uses: dante-ev/latex-action@latest
        with:
          working-directory: src
          root_file: main.tex
          compiler: biber
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          working-directory: src
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape -file-line-error
      - name: upload pdf
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: src/main.pdf
